# Generated by Django 5.1 on 2024-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_paymentpending_delete_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpending',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
